### ISSUE TITLE
 Create repository policies

### ISSUE THREAD

**Issue by byronkamal** [fga-eps-mds/2019.2-Gymnasteg-Wiki#11]
## Description
Creating repository policies to guide how to work and organize the repository

## Tasks
- [x] Branches Policy
- [x] Commit Policy
- [x] Code of Conduct
- [x] Contribution Policy

**Comment by IgorVeludo2** [comment]
Code of conduct was done in 7072a7658af36d9faa12578bdc0965c5849be9b2

**Comment by IgorVeludo2** [comment]
Contribution policy was done in 5766986f049187b111c2200fa0c274c991aaaa81
