### ISSUE TITLE
Refatoração de código 

### ISSUE THREAD

**Issue by ritzare** [fga-eps-mds/2019.2-Gymnasteg-Wiki#117]
## Descrição

Refatorar código de acordo com as issues 

## Tarefas

- [x] Ver as issues abertas no code climate (Clicar na badge no readme)

## Bugs a serem corrigidos:
- [x] Tela de Login buga quando tenta entrar com usuário não existente
- [x] Update de bancas não está gravando no banco
- [x] Validação nos campos
- [x] Corrigir o menu drawer para esconder quando mudar de rota
- [x] Retirar botão de CSV para cadastrar Árbitros e Atletas

**Comment by byronkamal** [comment]
@LuizPettengill @Fealps Alocado para Sprint 11

**Comment by byronkamal** [comment]
@alan-ms Para ver os problemas basta clicar na badge do Codeclimate que está nos README dos repositórios.
