### ISSUE TITLE
Create Vision Doc

### ISSUE THREAD

**Issue by byronkamal** [fga-eps-mds/2019.2-Gymnasteg-Wiki#18]
## Description
Create vision document to provide a broad view of the product to be developed.

## Tasks
- [x] Create template

**Comment by fabmont** [comment]
O commit 86dfa5883320d92d1cb1f24fb956499f28007138 implementa alguns tópicos do documento de visão.

**Comment by Felizolinha** [comment]
Eu(@Felizolinha), @fellipe-araujo e @LuizPettengill preenchemos o restante dos campos do documento de visão.
