### ISSUE TITLE
Git training

### ISSUE THREAD

**Issue by IgorVeludo2** [fga-eps-mds/2019.2-Gymnasteg-Wiki#2]
Introduction git for leveling team members.

**When:** 22/08 13h-14h

**Comment by byronkamal** [comment]
Git traning done.

**Comment by byronkamal** [comment]
References to study:
- https://danielkummer.github.io/git-flow-cheatsheet/index.pt_BR.html
- https://fjorgemota.com/git-flow-uma-forma-legal-de-organizar-repositorios-git/
- https://fjorgemota.com/versionamento-semantico-ou-como-versionar-software/
