### ISSUE TITLE
Criar documento de abertura de projeto (TAP)

### ISSUE THREAD

**Issue by IgorVeludo2** [fga-eps-mds/2019.2-Gymnasteg-Wiki#20]
Criar documento de abertura de projeto. Alguns exemplos podem ser encontrados [aqui](https://github.com/fga-eps-mds/A-Disciplina/blob/master/GPP_Material/04%20-%20inicializacao/Project-Charter.doc).

**Tarefas**
- [x] Introdução
- [x] Descrição do projeto
- [x] Propósito e justificativa
- [x] Restrições de projeto
- [x] Custo do projeto
- [x] Partes interessadas
- [x] Resumo de cronograma de marcos
- [x] Referências

**Comment by ritzare** [comment]
TAP disponível em [AQUI](fedb99f781403d41d7cde2c2b6884050d336a826)
