### ISSUE TITLE
Criar estrutura analítica do projeto (EAP)

### ISSUE THREAD

**Issue by IgorVeludo2** [fga-eps-mds/2019.2-Gymnasteg-Wiki#21]
**Tarefas**
- [x] Criar diagrama
- [x] Criar descrição

**Comment by IgorVeludo2** [comment]
Criação do diagrama disponível [aqui](541d3d04a0e95953a7506307767cb33ee445e1df)
Descrição disponível [aqui](095b461468f65c7209a42605b29243cf10e45424)

**Comment by byronkamal** [comment]
Reabrindo para linkar no pull request
