### ISSUE TITLE
Elicitação de requisitos

### ISSUE THREAD

**Issue by IgorVeludo2** [fga-eps-mds/2019.2-Gymnasteg-Wiki#22]
Elicitar os requisitos funcionais e não funcionais do sistema.

**Tarefas**
- [x] Descrição das técnicas utilizadas
- [x] Requisitos elicitados

**Comment by byronkamal** [comment]
O grupo se reuniu no sábado (07/09) durante a reunião de sprint para fazer as elicitações dos requisitos. Umas das técnicas utilizadas foi a de BrainStorm.
