### ISSUE TITLE
Criar plano de gerenciamento de riscos 

### ISSUE THREAD

**Issue by ritzare** [fga-eps-mds/2019.2-Gymnasteg-Wiki#37]
### Criar plano de gerenciamento de riscos 

O plano de gerenciamento de riscos visa prever os riscos que o projeto pode enfrentar e através dele minimizar ou extinguir os possíveis danos causados.

## Tarefas
- [ ] Criar plano de gerenciamento de riscos

**Comment by byronkamal** [comment]
#41
