### ISSUE TITLE
US05#Cadastro de Atletas(Planilhas)

### ISSUE THREAD

**Issue by Felizolinha** [fga-eps-mds/2019.2-Gymnasteg-Wiki#43]
## Descrição
Eu, como **coordenador**, desejo **cadastrar vários atletas utilizando uma única planilha** para **cadastrá-los eficiententemente**.

**Tarefas**
- [ ] Definir colunas da tabela
- [ ] Criar interface para fazer upload de arquivos .csv
- [ ] Mostrar erros na interface
- [ ] Receber e ler o arquivo .csv no servidor, realizando o cadastro dos atletas no banco de dados
 

**Fluxo de exceção:**
- [ ] Mostrar erros de conexão com o servidor.
- [ ] Mostrar erro caso o usuário tente fazer upload de um arquivo do tipo errado.
- [ ] Mostrar erro caso o arquivo .csv esteja corrompido.
- [ ] Mostrar erro caso o arquivo .csv não contenha todas as colunas necessárias.
- [ ] Mostrar erro caso algum dado da planilha seja do tipo errado.
- [ ] Mostrar erro caso algum dado da planilha seja inválido.
- [ ] Retornar erro caso o banco de dados falhe em algum momento do cadastro de atletas.

**Comment by byronkamal** [comment]
Não se aplica mais ao escopo, por causa de tempo e viabilidade.
