### ISSUE TITLE
US07#Cadastro de Árbitro (planilha)

### ISSUE THREAD

**Issue by alan-ms** [fga-eps-mds/2019.2-Gymnasteg-Wiki#46]
## Descrição
Eu, como **Coordenador**, desejo **enviar um arquivo csv** para **cadastro de árbitros na banca**.
- [ ] Apresentar a opção de upload do arquivo csv com os dados dos árbitros
- [ ] Enviar o arquivo csv para API
- [ ] Cadastrar os árbitros da banca no banco de dados
- [ ] Mensagem de suceso
 

Fluxo de exceção:
- [ ] Exibir mensagem de erro caso o arquivo não tenha formato csv ou não seja encontrado
- [ ] Exibir mensagem de erro caso o arquivo csv tenha fora do padrão de csv para cadastro dos árbitros na banca

**Comment by Felizolinha** [comment]
Eu e o @fellipe-araujo decidimos por não guardar a senha do árbitro em forma de hash para que ela possa ser recuperada pelo Coordenador depois, caso haja a necessidade de reenviá-la para o árbitro.

Como a senha(gerada automaticamente) só é necessária durante a competição, e depois descartada, não deve causar maiores problemas.

**Comment by fabmont** [comment]
No repositório do front-end, criei a branch chamada "feature/46-US07#CadastroDeArbitro" e subi alguns componentes que facilitarão no desenvolvimento. A tela de opção de cadastro já foi implementada nesta leva, bastando apenas a implementação das telas em si de cada opção (arquivo .csv/cadastro manual)

**Comment by Felizolinha** [comment]
> No repositório do front-end, criei a branch chamada "feature/46-US07#CadastroDeArbitro" e subi alguns componentes que facilitarão no desenvolvimento. A tela de opção de cadastro já foi implementada nesta leva, bastando apenas a implementação das telas em si de cada opção (arquivo .csv/cadastro manual)

Eu e o @LuizPettengill estávamos trabalhando na branch `feature/69-US06#CadastroDeArbitros` por estarmos começando pela issue #69. Coincidentemente, criamos um componente com o mesmo nome que o seu, `CadastroArbitros`, para a tela de Cadastro de Árbitros por formulário, alguma ideia de como juntar as duas?

**Comment by fabmont** [comment]
Caso queiram manter a tela de vocês completamente, aconselho fazer merge da branch que criei na que vocês criaram, e caso haja conflito no componente `CadastroArbitros`, escolham manter o de vocês. Digo isso pois além deste componente, implementei alguns ajustes de rotas no front-end e alguns facilitadores como uma pagina genérica para conter o conteúdo das páginas, etc.

**Comment by byronkamal** [comment]
Não se aplica mais ao escopo, por causa de tempo e viabilidade.
