### ISSUE TITLE
Criar protótipo de alta fidelidade.

### ISSUE THREAD

**Issue by IgorVeludo2** [fga-eps-mds/2019.2-Gymnasteg-Wiki#55]
## Descrição

Essa issue serve para a criação do protótipo de alta fidelidade afim de que o grupo o use como base para a criação da aplicação.

## Tarefas

Nesta parte, você deve listar os critérios de aceitação necessários para resolver a issue.
Ex:

- [ ] Criar protótipo de alta fidelidade

**Comment by fabmont** [comment]
O link abaixo torna possível a visualização/navegação do protótipo de alta fidelidade:
https://shorturl.at/uyIU5

Subiremos de forma continua todas as alterações/atualizações no protótipo.

**Comment by Fealps** [comment]
Documento com as imagens e interações do protótipo foram commitados
