### ISSUE TITLE
US01#CadastroDaBanca - Unir o frontend com o backend

### ISSUE THREAD

**Issue by alan-ms** [fga-eps-mds/2019.2-Gymnasteg-Wiki#66]
## Descrição

Parear backend com o frontend a funcionalidade de cadastrar banca, verificando se a banca foi cadastra corretamente no banco de dados.

**Tarefas**
- [ ] Usar a rota `GET /modalidades` para pegar as modalidades do banco de dados.
- [ ] Fazer o request de cadastro de banca para `POST /bancas`.
- [ ] Mostrar erro caso ocorra algum erro de validação de informação de cadastro da banca.

**Comment by byronkamal** [comment]
Reabertura de issue, pois os PR's ainda não forma aceitos.
