### ISSUE TITLE
US06#Cadastro de árbitro (forms)

### ISSUE THREAD

**Issue by LuizPettengill** [fga-eps-mds/2019.2-Gymnasteg-Wiki#69]
## Descrição

Eu, como **coordenador**, desejo **preencher um formulário** para **cadastrar os árbitros**.

**Tarefas**
- [x] Mostrar título "Cadastro dos Árbitros"
- [x] Criar campo de nome
- [x] Criar campo de email
- [x] Botão de cadastrar
- [x] Limpar campos de input após cadastrar um novo árbitro
- [x] Mostrar erros na tela, caso ocorram
- [x] Enviar os dados para a API
    - [x] Desabilitar botão de cadastro enquanto o request estiver sendo feito

Fluxo de exceção:

- [x] Email inválido
- [x] Árbitro já cadastrado
- [x] Falta de conexão com a internet
- [x] Falha na conexão com o servidor (servidor offline)
- [x] Falha ao cadastrar o árbitro (falha no banco de dados)

**Comment by Felizolinha** [comment]
Segue link mostrando [como detectar um erro de conexão quando estiver utilizando o axios](https://github.com/axios/axios/issues/383#issuecomment-234079506).
