### ISSUE TITLE
Atualizar o protótipo 

### ISSUE THREAD

**Issue by byronkamal** [fga-eps-mds/2019.2-Gymnasteg-Wiki#87]
## Descrição
Atualizar protótipo de alta fidelidade para incluir novas telas.

## Tarefas

Nesta parte, você deve listar os critérios de aceitação necessários para resolver a issue.

- [x] Tela para o árbitro olhar as bancas em que votará
- [x] Tela para o árbitro selecionar em qual atleta irá votar
- [x] Tela de votação (Árbitro)
- [x] Atualizar telas já existentes para acompanhar as mudanças do projeto

**Comment by Felizolinha** [comment]
Link do protótipo atualizado: [https://xd.adobe.com/view/faba8bd3-a710-4863-5745-c9d8d8a26a6b-8c8b/](https://xd.adobe.com/view/faba8bd3-a710-4863-5745-c9d8d8a26a6b-8c8b/)

**Comment by Felizolinha** [comment]
Link para desenvolvimento: https://xd.adobe.com/spec/08eb49a9-5dca-4e5b-50ca-ff3266c626bc-7eda/
